[build]
  command = "bash ./netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--force --no-optional"
  GIT_SUBMODULE_STRATEGY = "none"
  NPM_VERSION = "9.8.1"

[build.processing]
  skip_processing = true

# Configurações de desenvolvimento
[dev]
  publish = "dist"
  targetPort = 5173
  framework = "vite"

# Redirecionamentos
[[redirects]]
  from = "/dist/*"
  to = "/"
  status = 404

# Configurações de build
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
