[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  GIT_SUBMODULE_STRATEGY = "none"

# Configurações de desenvolvimento
[dev]
  publish = "dist"
  targetPort = 5173
  framework = "vite"

# Redirecionamentos
[[redirects]]
  from = "/dist/*"
  to = "/"
  status = 404

# Configurações de build
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
