[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD origin/main -- netlify.toml"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"
  NPM_FLAGS = "--no-optional"
  GIT_SUBMODULE_STRATEGY = "none"

# Configurações de desenvolvimento
[dev]
  publish = "dist"
  targetPort = 5173
  framework = "vite"

# Plugins
[[plugins]]
  package = "@netlify/plugin-git-credential-helper"

# Redirecionamentos
[[redirects]]
  from = "/dist/*"
  to = "/"
  status = 404

# Configurações de build adicionais
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
